class CountryCode {
  final String name;
  final String code;
  final String dialCode;

  const CountryCode({
    required this.name,
    required this.code,
    required this.dialCode,
  });
}

const allCountryCodes = [
  CountryCode(name: 'السودان', code: 'SD', dialCode: '+249'),
  CountryCode(name: 'المملكة العربية السعودية', code: 'SA', dialCode: '+966'),
  CountryCode(name: 'الإمارات العربية المتحدة', code: 'AE', dialCode: '+971'),
  CountryCode(name: 'مصر', code: 'EG', dialCode: '+20'),
  CountryCode(name: 'قطر', code: 'QA', dialCode: '+974'),
  CountryCode(name: 'الكويت', code: 'KW', dialCode: '+965'),
  CountryCode(name: 'البحرين', code: 'BH', dialCode: '+973'),
  CountryCode(name: 'عمان', code: 'OM', dialCode: '+968'),
  CountryCode(name: 'العراق', code: 'IQ', dialCode: '+964'),
  CountryCode(name: 'الأردن', code: 'JO', dialCode: '+962'),
  CountryCode(name: 'لبنان', code: 'LB', dialCode: '+961'),
  CountryCode(name: 'فلسطين', code: 'PS', dialCode: '+970'),
  CountryCode(name: 'سوريا', code: 'SY', dialCode: '+963'),
  CountryCode(name: 'اليمن', code: 'YE', dialCode: '+967'),
  CountryCode(name: 'ليبيا', code: 'LY', dialCode: '+218'),
  CountryCode(name: 'تونس', code: 'TN', dialCode: '+216'),
  CountryCode(name: 'الجزائر', code: 'DZ', dialCode: '+213'),
  CountryCode(name: 'المغرب', code: 'MA', dialCode: '+212'),
  CountryCode(name: 'موريتانيا', code: 'MR', dialCode: '+222'),
  CountryCode(name: 'الصومال', code: 'SO', dialCode: '+252'),
  CountryCode(name: 'جيبوتي', code: 'DJ', dialCode: '+253'),
  CountryCode(name: 'جزر القمر', code: 'KM', dialCode: '+269'),
  CountryCode(name: 'تركيا', code: 'TR', dialCode: '+90'),
  CountryCode(name: 'إيران', code: 'IR', dialCode: '+98'),
  CountryCode(name: 'باكستان', code: 'PK', dialCode: '+92'),
  CountryCode(name: 'الهند', code: 'IN', dialCode: '+91'),
  CountryCode(name: 'بنغلاديش', code: 'BD', dialCode: '+880'),
  CountryCode(name: 'أفغانستان', code: 'AF', dialCode: '+93'),
  CountryCode(name: 'إندونيسيا', code: 'ID', dialCode: '+62'),
  CountryCode(name: 'ماليزيا', code: 'MY', dialCode: '+60'),
  CountryCode(name: 'سنغافورة', code: 'SG', dialCode: '+65'),
  CountryCode(name: 'الفلبين', code: 'PH', dialCode: '+63'),
  CountryCode(name: 'تايلاند', code: 'TH', dialCode: '+66'),
  CountryCode(name: 'فيتنام', code: 'VN', dialCode: '+84'),
  CountryCode(name: 'الصين', code: 'CN', dialCode: '+86'),
  CountryCode(name: 'اليابان', code: 'JP', dialCode: '+81'),
  CountryCode(name: 'كوريا الجنوبية', code: 'KR', dialCode: '+82'),
  CountryCode(name: 'أستراليا', code: 'AU', dialCode: '+61'),
  CountryCode(name: 'نيوزيلندا', code: 'NZ', dialCode: '+64'),
  CountryCode(name: 'الولايات المتحدة', code: 'US', dialCode: '+1'),
  CountryCode(name: 'كندا', code: 'CA', dialCode: '+1'),
  CountryCode(name: 'المملكة المتحدة', code: 'GB', dialCode: '+44'),
  CountryCode(name: 'فرنسا', code: 'FR', dialCode: '+33'),
  CountryCode(name: 'ألمانيا', code: 'DE', dialCode: '+49'),
  CountryCode(name: 'إيطاليا', code: 'IT', dialCode: '+39'),
  CountryCode(name: 'إسبانيا', code: 'ES', dialCode: '+34'),
  CountryCode(name: 'البرتغال', code: 'PT', dialCode: '+351'),
  CountryCode(name: 'هولندا', code: 'NL', dialCode: '+31'),
  CountryCode(name: 'بلجيكا', code: 'BE', dialCode: '+32'),
  CountryCode(name: 'سويسرا', code: 'CH', dialCode: '+41'),
  CountryCode(name: 'النمسا', code: 'AT', dialCode: '+43'),
  CountryCode(name: 'السويد', code: 'SE', dialCode: '+46'),
  CountryCode(name: 'النرويج', code: 'NO', dialCode: '+47'),
  CountryCode(name: 'الدنمارك', code: 'DK', dialCode: '+45'),
  CountryCode(name: 'فنلندا', code: 'FI', dialCode: '+358'),
  CountryCode(name: 'اليونان', code: 'GR', dialCode: '+30'),
  CountryCode(name: 'روسيا', code: 'RU', dialCode: '+7'),
  CountryCode(name: 'أوكرانيا', code: 'UA', dialCode: '+380'),
  CountryCode(name: 'بولندا', code: 'PL', dialCode: '+48'),
  CountryCode(name: 'جمهورية التشيك', code: 'CZ', dialCode: '+420'),
  CountryCode(name: 'سلوفاكيا', code: 'SK', dialCode: '+421'),
  CountryCode(name: 'المجر', code: 'HU', dialCode: '+36'),
  CountryCode(name: 'رومانيا', code: 'RO', dialCode: '+40'),
  CountryCode(name: 'بلغاريا', code: 'BG', dialCode: '+359'),
  CountryCode(name: 'صربيا', code: 'RS', dialCode: '+381'),
  CountryCode(name: 'البوسنة والهرسك', code: 'BA', dialCode: '+387'),
  CountryCode(name: 'ألبانيا', code: 'AL', dialCode: '+355'),
  CountryCode(name: 'جنوب أفريقيا', code: 'ZA', dialCode: '+27'),
  CountryCode(name: 'نيجيريا', code: 'NG', dialCode: '+234'),
  CountryCode(name: 'كينيا', code: 'KE', dialCode: '+254'),
  CountryCode(name: 'إثيوبيا', code: 'ET', dialCode: '+251'),
  CountryCode(name: 'تنزانيا', code: 'TZ', dialCode: '+255'),
  CountryCode(name: 'أوغندا', code: 'UG', dialCode: '+256'),
  CountryCode(name: 'غانا', code: 'GH', dialCode: '+233'),
  CountryCode(name: 'الكاميرون', code: 'CM', dialCode: '+237'),
  CountryCode(name: 'ساحل العاج', code: 'CI', dialCode: '+225'),
  CountryCode(name: 'السنغال', code: 'SN', dialCode: '+221'),
  CountryCode(name: 'مالي', code: 'ML', dialCode: '+223'),
  CountryCode(name: 'تشاد', code: 'TD', dialCode: '+235'),
  CountryCode(name: 'البرازيل', code: 'BR', dialCode: '+55'),
  CountryCode(name: 'الأرجنتين', code: 'AR', dialCode: '+54'),
  CountryCode(name: 'المكسيك', code: 'MX', dialCode: '+52'),
  CountryCode(name: 'كولومبيا', code: 'CO', dialCode: '+57'),
  CountryCode(name: 'تشيلي', code: 'CL', dialCode: '+56'),
  CountryCode(name: 'بيرو', code: 'PE', dialCode: '+51'),
];
